Revert "adb: add transport benchmark."
This reverts commit 8fd4e95ac3270ecff85f90952c4ad53ac662efed [formerly d78f59ca53746b9ffa5e44dd5f0ca636ce4012d4].

Reason for revert: Breaks aosp-master renderscript and sdk_mac:
  error: system/core/adb/Android.bp:199:19: unrecognized property "host_supported"

Change-Id: Ifd75921dcdf5dce57f98833a913540914984b293